Removing the System.loadLibrary('gdaljni')
This is not the role of this lib to load it, this has to be done by the
gdal/ogr jar bindings. This presumably could cause issues in some
specific classloading environments (tomcat with several webapps using
the same jars)

If you have a look at gdal sources (generated swig bindings):
swig/java/org/src/gdal/gdal/gdalJNI.java:18:      System.loadLibrary("gdaljni");

The lib should already be loaded there ; this might cause these kind of
messages into Tomcat logs (tested with 2 webapps making use of
imageio-ext):

Native library load failed.
java.lang.UnsatisfiedLinkError: Native Library [...]libgdaljni[...] already loaded in another classloader